/*
# brease API Test Suite
---
This test suite uses [httpyac](https://httpyac.github.io) and [anweber.httpbook](https://marketplace.visualstudio.com/items?itemName=anweber.httpbook).
Authentication is done by root api key for simplicity.
*/
# @name allRules
# @description read all rules to make sure context is empty
GET {{host}}/{{contextID}}/rules
x-api-key: {{apiKey}}
x-org-id: {{orgID}}

?? status == 200
?? duration < 200
{{
  const { expect } = require('chai');
  test('no rules exist', () => {
    expect(response.parsedBody).to.be.an('object');
    expect(response.parsedBody.rules).to.equal(null);
  });
}}

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
x-request-id: 188f22c7-df1e-4468-a873-d6619043dac4
date: Sun, 27 Aug 2023 18:46:25 GMT
content-length: 37
connection: close
###
# @name addRule
# @description create first rule
POST {{host}}/{{contextID}}/rules/add
x-api-key: {{apiKey}}
x-org-id: {{orgID}}
{
	"rule": {
		"actions": [
			{
				"action": "$set",
				"target": {
					"target": "targetIDString",
					"kind": "targetTypeString",
					"value": "ZXhhbXBsZQ=="
				}
			}
		],
		"action": "actionString",
		"description": "descriptionString",
		"expression": {
			"and": {
				"expression": [
					{
						"condition": {
							"key": "$.first_name",
							"kind": "hv"
						}
					},
					{
						"condition": {
							"key": "$.birthdate",
							"kind": "rgx",
							"value": "IlxcZHsyfS9cXGR7Mn0vMjBcXGR7Mn0i"
						}
					},
					{
						"condition": {
							"key": "$.email",
							"kind": "sx",
							"value": "Ii5nb3Yi"
						}
					},
					{
						"condition": {
							"key": "$.age",
							"kind": "px",
							"value": "OQ=="
						}
					},
					{
						"condition": {
							"key": "$.company_name",
							"kind": "eq",
							"value": "IkxpdmVmaXNoIg=="
						}
					},
					{
						"condition": {
							"key": "$.country",
							"kind": "in",
							"value": "WyJVa3JhaW5lIl0="
						}
					},
					{
						"condition": {
							"key": "$.favorite_color",
							"kind": "some",
							"value": "WyJyZWQiXQ=="
						}
					},
					{
						"condition": {
							"key": "$.favorite_color",
							"kind": "none",
							"value": "WyJibHVlIl0="
						}
					},
					{
						"condition": {
							"key": "$.favorite_color",
							"kind": "all",
							"value": "WyJyZWQiLCJncmVlbiJd"
						}
					}
				]
			}
		},
		"id": "asdf"
	}
}

?? status == 200
?? duration < 200

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
x-request-id: 03d2afd1-2d74-4cac-b04c-aaa8d2caf8c3
date: Sun, 27 Aug 2023 18:46:25 GMT
connection: close
transfer-encoding: chunked
###
# @name oneVersionOnly
# @description ensure only 1 version exists
GET {{host}}/{{contextID}}/rules/{{ruleID}}/versions
x-api-key: {{apiKey}}
x-org-id: {{orgID}}

?? status == 200
?? duration < 50
{{
  const { expect } = require('chai');
  test('only one version exists', () => {
    const body = response.parsedBody
    expect(body).to.be.an('object');
    expect(body.versions.length).to.equal(1);
  });
}}

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
x-request-id: 67b6c3e2-b76d-4625-b701-b6bc755651dd
date: Sun, 27 Aug 2023 18:46:25 GMT
connection: close
transfer-encoding: chunked
###
# @name updateRule
# @description update existing rule
PUT {{host}}/{{contextID}}/rules/{{ruleID}}
x-api-key: {{apiKey}}
x-org-id: {{orgID}}
{
	"rule": {
		"actions": [
			{
				"action": "$set",
				"target": {
					"target": "$.prop",
					"kind": "customTargetKind",
					"value": "ZXhhbXBsZQ=="
				}
			}
		],
		"action": "actionString",
		"description": "descriptionString",
		"expression": {
			"and": {
				"expression": [
					{
						"condition": {
							"key": "$.first_name",
							"kind": "hv"
						}
					},
					{
						"condition": {
							"key": "$.birthdate",
							"kind": "rgx",
							"value": "IlxcZHsyfS9cXGR7Mn0vMjBcXGR7Mn0i"
						}
					},
					{
						"condition": {
							"key": "$.email",
							"kind": "sx",
							"value": "Ii5nb3Yi"
						}
					},
					{
						"condition": {
							"key": "$.age",
							"kind": "px",
							"value": "OQ=="
						}
					},
					{
						"condition": {
							"key": "$.company_name",
							"kind": "eq",
							"value": "IkxpdmVmaXNoIg=="
						}
					},
					{
						"condition": {
							"key": "$.country",
							"kind": "in",
							"value": "WyJVa3JhaW5lIl0="
						}
					},
					{
						"condition": {
							"key": "$.favorite_color",
							"kind": "some",
							"value": "WyJyZWQiXQ=="
						}
					},
					{
						"condition": {
							"key": "$.favorite_color",
							"kind": "none",
							"value": "WyJibHVlIl0="
						}
					},
					{
						"condition": {
							"key": "$.favorite_color",
							"kind": "all",
							"value": "WyJyZWQiLCJncmVlbiJd"
						}
					}
				]
			}
		},
		"id": "asdf"
	}
}

?? status == 200
?? duration < 100

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
x-request-id: 1ba00cd4-c4d7-4542-aee6-ef64c7458e65
date: Sun, 27 Aug 2023 18:46:25 GMT
connection: close
transfer-encoding: chunked
###
# @name twoVersions
# @description ensure 2 versions of rule exist
GET {{host}}/{{contextID}}/rules/{{ruleID}}/versions
x-api-key: {{apiKey}}
x-org-id: {{orgID}}

?? status == 200
?? duration < 50
{{
  const { expect } = require('chai');
  test('two versions available', () => {
    const body = response.parsedBody
    expect(body).to.be.an('object');
    expect(body.versions.length).to.equal(2);
  });
}}

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
x-request-id: 952e55b3-4e77-4f02-81c3-82ebc5e91b6f
date: Sun, 27 Aug 2023 18:46:25 GMT
connection: close
transfer-encoding: chunked
###
# @name evaluate
# @description evaluation on sample object
POST {{host}}/{{contextID}}/evaluate
x-api-key: {{apiKey}}
x-org-id: {{orgID}}
{
	"object": {
		"user_id": 1,
		"first_name": "Gusella",
		"last_name": "Dakers",
		"email": "gdakers0@va.gov",
		"age": 98,
		"gender": "Female",
		"address": "248 Parkside Hill",
		"city": "Komysh-Zorya",
		"state": null,
		"country": "Ukraine",
		"phone_number": "419-767-5757",
		"job_title": "Financial Advisor",
		"company_name": "Livefish",
		"favorite_color": [
			"green",
			"red"
		],
		"birthdate": "11/12/2021"
	}
}

?? status == 200
?? duration < 50
{{
  const { expect } = require('chai');
  test('expected result', () => {
    const body = response.parsedBody
    expect(body).to.be.an('object');
	
    expect(body.results.length).to.equal(1);
    expect(body.results[0].action).to.equal("$set");
    expect(body.results[0].target.kind).to.equal("customTargetKind");
    expect(body.results[0].target.target).to.equal("$.prop");
    expect(body.results[0].target.value).to.equal("ZXhhbXBsZQ==");

  });
}}

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
x-request-id: 7bfc9617-b3b7-4160-b507-92af2d0e2bd3
date: Sun, 27 Aug 2023 18:46:25 GMT
content-length: 260
connection: close
###
# @name removeRule
# @description can remove rule
DELETE {{host}}/{{contextID}}/rules/{{ruleID}}
x-api-key: {{apiKey}}
x-org-id: {{orgID}}

?? status == 200
?? duration < 50

HTTP/1.1 200  - OK
content-type: text/plain; charset=utf-8
x-request-id: efb89880-edeb-49c8-9768-0a209d03cd91
date: Sun, 27 Aug 2023 18:46:25 GMT
content-length: 0
connection: close
###
# @name noVersions
# @description Ensure there are no versions of rule
GET {{host}}/{{contextID}}/rules/{{ruleID}}/versions
x-api-key: {{apiKey}}
x-org-id: {{orgID}}

?? status == 200
?? duration < 50
{{
  const { expect } = require('chai');
  test('no versions for rule', () => {
    const body = response.parsedBody
    expect(body).to.be.an('object');
    expect(body.versions.length).to.equal(null);
  });
}}

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
x-request-id: 516d8498-1d66-48c1-a99c-9f997302051b
date: Sun, 27 Aug 2023 18:46:53 GMT
content-length: 24
connection: close
###
# @name emptyContext
# @description make sure there are no rules left in context
GET {{host}}/{{contextID}}/rules
x-api-key: {{apiKey}}
x-org-id: {{orgID}}

?? status == 200
?? duration < 200
{{
  const { expect } = require('chai');
  test('no rules in context', () => {
    expect(response.parsedBody).to.be.an('object');
    expect(response.parsedBody.rules).to.equal(null);
  });
}}

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
x-request-id: 24c55a00-3afe-4403-921c-c2b0a866d9ba
date: Sun, 27 Aug 2023 18:46:25 GMT
content-length: 37
connection: close